version: '3'
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      EULA: 'TRUE'
      MEMORY: 3G
      EXISTING_WHITELIST_FILE: SYNCHRONIZE
      WHITELIST: |
        Abattoir
      EXISTING_OPS_FILE: SYNCHRONIZE
      OPS: |
        Abattoir
    volumes:
      - /mnt/efs/data:/data