version: '3'
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      EULA: 'TRUE'
      MEMORY: 3G
      EXISTING_WHITELIST_FILE: SYNCHRONIZE
      WHITELIST: |
        Abattoir
      EXISTING_OPS_FILE: SYNCHRONIZE
      OPS: |
        Abattoir
    volumes:
      - /mnt/efs/data:/data
  bluemap:
    image: ghcr.io/bluemap-minecraft/bluemap:latest
    restart: always
    command: -r -u -w
    ports:
      - '8100:8100'
    volumes:
      - '/mnt/efs/bluemap/config:/app/config'
      - '/mnt/efs/data/world:/app/world'
#      - '/mnt/efs/data/world_nether:/app/world_nether'
#      - '/mnt/efs/world_the_end:/app/world_the_end'
      - '/mnt/efs/bluemap/data:/app/data'
      - '/mnt/efs/bluemap/web:/app/web'